# Generated by Django 2.2.12 on 2020-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataroles',
            options={'verbose_name': 'Roles de Usuarios', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Datos de Ususrios', 'verbose_name_plural': 'Información'},
        ),
        migrations.AlterModelOptions(
            name='habiuser',
            options={'verbose_name': 'Habilidades de Usuarios', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Nivel de habilidad', 'verbose_name_plural': 'Niveles de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Perfiles de Usuarios', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='habiuser',
            name='DescHabil',
            field=models.TextField(max_length=2000, verbose_name='Descripcion de la habilidad'),
        ),
    ]
