# Generated by Django 2.2.12 on 2020-05-14 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0003_auto_20200513_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoriaProyecto', models.CharField(max_length=20, verbose_name='Identificador')),
                ('lenguaje', models.CharField(max_length=200, verbose_name='Lenguaje')),
                ('motorBd', models.CharField(max_length=200, verbose_name='Motor De Base De Datos')),
                ('arquitectura', models.CharField(max_length=200, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Datos de Categoria',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoDocumento', models.CharField(max_length=200, verbose_name='Tipo Documento')),
                ('nomDocumento', models.CharField(max_length=200, verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Tipo De Documento',
                'verbose_name_plural': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProyecto', models.CharField(max_length=200, null=True, verbose_name='Nombre de Proyecto')),
                ('desProyecto', models.TextField(max_length=200, null=True, verbose_name='Descripcion de Proyecto')),
                ('imgProyecto', models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Imagen de Proyecto')),
                ('fechaInicial', models.DateTimeField(auto_now=True)),
                ('fechaFinal', models.DateTimeField(auto_now=True)),
                ('urlReposotorio', models.CharField(max_length=200, null=True, verbose_name='Url Repositorio')),
                ('estProyecto', models.CharField(max_length=200, null=True, verbose_name='Estado del Proyecto')),
                ('idCategoriaProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CateProyecto')),
            ],
            options={
                'verbose_name': 'Datos del Proyecto',
                'verbose_name_plural': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocumento', models.CharField(max_length=200, null=True, verbose_name='Nombre de Documento')),
                ('pathDocument', models.CharField(max_length=200, null=True, verbose_name='Path Documento')),
                ('idProyectoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto')),
                ('idTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Datos del Documento',
                'verbose_name_plural': 'Documento',
            },
        ),
    ]
